//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭКЗАМЕН_ГОЛОВИН.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OOO_RULEntities2 : DbContext
    {
        public OOO_RULEntities2()
            : base("name=OOO_RULEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<DIski> DIski { get; set; }
        public virtual DbSet<Dvorniki> Dvorniki { get; set; }
        public virtual DbSet<Fonarik> Fonarik { get; set; }
        public virtual DbSet<Kolonki> Kolonki { get; set; }
        public virtual DbSet<Kovrik> Kovrik { get; set; }
        public virtual DbSet<Oil> Oil { get; set; }
        public virtual DbSet<Perchatki> Perchatki { get; set; }
        public virtual DbSet<Rul> Rul { get; set; }
        public virtual DbSet<VD> VD { get; set; }
        public virtual DbSet<Autorization> Autorization { get; set; }
        public virtual DbSet<Shop_auto_product> Shop_auto_product { get; set; }
    }
}
