//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭКЗАМЕН_ГОЛОВИН.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_auto_product
    {
        public int ID_Rul { get; set; }
        public int ID_Dvornikov { get; set; }
        public int ID_Fonarik { get; set; }
        public int ID_Oil { get; set; }
        public int ID_Kovrik { get; set; }
        public int ID_Diskov { get; set; }
        public int ID_VD { get; set; }
        public int ID_Perchatki { get; set; }
        public int ID_Kolonki { get; set; }
        public int ID_Admin { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual DIski DIski { get; set; }
        public virtual Dvorniki Dvorniki { get; set; }
        public virtual Fonarik Fonarik { get; set; }
        public virtual Kolonki Kolonki { get; set; }
        public virtual Kovrik Kovrik { get; set; }
        public virtual Oil Oil { get; set; }
        public virtual Perchatki Perchatki { get; set; }
        public virtual Rul Rul { get; set; }
        public virtual VD VD { get; set; }
    }
}
